import React, { useState } from "react";
import { ColorModeSwitcher } from "../components/ColorModeSwitcher"
import { ProSidebar, Menu, MenuItem, SubMenu, SidebarHeader, SidebarFooter, SidebarContent } from 'react-pro-sidebar';
import 'react-pro-sidebar/dist/css/styles.css';
import { FaGem, FaHeart } from "react-icons/fa";
import { Button, Switch, Text } from "@chakra-ui/react";
import Sidebar from "../components/Sidebar";

export const Home = () => {
    return (
        <div>
            <Text fontSize='xl'>Lorem ipsum dolor sit amet, consectetur adipiscing elit, sed do eiusmod tempor incididunt ut labore et dolore magna aliqua. Justo donec enim diam vulputate ut pharetra sit amet. Mattis vulputate enim nulla aliquet porttitor lacus luctus accumsan. Lacus suspendisse faucibus interdum posuere lorem ipsum dolor sit. Quis blandit turpis cursus in hac habitasse. Vitae suscipit tellus mauris a diam maecenas sed enim. Magna sit amet purus gravida quis blandit turpis. Ut sem viverra aliquet eget. Iaculis urna id volutpat lacus laoreet. Consequat ac felis donec et odio. Ornare arcu dui vivamus arcu felis bibendum ut tristique et. Sit amet cursus sit amet dictum sit amet justo donec. Et tortor at risus viverra adipiscing at in. Turpis tincidunt id aliquet risus feugiat. Leo a diam sollicitudin tempor. Curabitur gravida arcu ac tortor dignissim convallis aenean. Risus feugiat in ante metus dictum at tempor commodo. Leo urna molestie at elementum eu facilisis sed odio. Consectetur adipiscing elit ut aliquam purus sit.

Nullam eget felis eget nunc lobortis mattis. Imperdiet proin fermentum leo vel orci porta non pulvinar. Imperdiet massa tincidunt nunc pulvinar sapien et ligula. Semper risus in hendrerit gravida. Id neque aliquam vestibulum morbi blandit cursus risus at ultrices. Eleifend donec pretium vulputate sapien nec sagittis. Donec adipiscing tristique risus nec feugiat in. Arcu dictum varius duis at consectetur. Tempor commodo ullamcorper a lacus vestibulum sed arcu non odio. Cursus euismod quis viverra nibh cras pulvinar mattis nunc. Viverra ipsum nunc aliquet bibendum enim.

In fermentum et sollicitudin ac. Aenean pharetra magna ac placerat vestibulum lectus mauris ultrices. Ac orci phasellus egestas tellus rutrum. Quis lectus nulla at volutpat diam ut venenatis. Ipsum consequat nisl vel pretium lectus quam id leo. At quis risus sed vulputate odio ut. Faucibus pulvinar elementum integer enim neque volutpat ac tincidunt vitae. Vestibulum morbi blandit cursus risus. Varius sit amet mattis vulputate enim nulla aliquet porttitor lacus. Ut etiam sit amet nisl purus in. Habitant morbi tristique senectus et netus. Adipiscing elit pellentesque habitant morbi tristique. Quam elementum pulvinar etiam non quam. Natoque penatibus et magnis dis parturient montes nascetur ridiculus. Lectus nulla at volutpat diam ut venenatis tellus. Pellentesque nec nam aliquam sem et tortor consequat. Ut tristique et egestas quis ipsum suspendisse ultrices. Ac tortor vitae purus faucibus ornare. At tellus at urna condimentum.

Placerat vestibulum lectus mauris ultrices. Sem nulla pharetra diam sit amet. Nunc faucibus a pellentesque sit amet porttitor eget dolor morbi. Sed felis eget velit aliquet sagittis id consectetur. Pharetra et ultrices neque ornare aenean euismod elementum. Venenatis cras sed felis eget velit. Vel orci porta non pulvinar neque. Lectus nulla at volutpat diam. Aliquam sem fringilla ut morbi tincidunt. At tellus at urna condimentum mattis pellentesque id. Id aliquet lectus proin nibh nisl condimentum id venenatis. Egestas pretium aenean pharetra magna ac placerat vestibulum lectus. Urna neque viverra justo nec ultrices dui sapien eget mi. Porttitor eget dolor morbi non arcu risus quis varius quam. Aliquet nibh praesent tristique magna sit amet purus gravida. Netus et malesuada fames ac turpis egestas sed tempus. Pharetra massa massa ultricies mi quis hendrerit dolor magna eget. Congue mauris rhoncus aenean vel elit scelerisque mauris.

Tristique nulla aliquet enim tortor at auctor urna. Quam adipiscing vitae proin sagittis nisl rhoncus. Laoreet sit amet cursus sit. At lectus urna duis convallis convallis tellus id interdum velit. Mattis ullamcorper velit sed ullamcorper morbi. Mi quis hendrerit dolor magna eget est lorem ipsum. Id porta nibh venenatis cras. Mollis aliquam ut porttitor leo. Tortor at auctor urna nunc id cursus metus aliquam. Consectetur libero id faucibus nisl tincidunt eget. Lectus magna fringilla urna porttitor rhoncus. Adipiscing elit pellentesque habitant morbi tristique senectus et. Adipiscing commodo elit at imperdiet dui. Ipsum dolor sit amet consectetur. Nascetur ridiculus mus mauris vitae ultricies. Interdum consectetur libero id faucibus nisl. Feugiat pretium nibh ipsum consequat nisl vel pretium lectus.

Donec adipiscing tristique risus nec feugiat. In massa tempor nec feugiat nisl pretium fusce id. Urna id volutpat lacus laoreet non curabitur gravida arcu. Sed enim ut sem viverra aliquet. Auctor eu augue ut lectus arcu. Fames ac turpis egestas integer eget aliquet. Posuere urna nec tincidunt praesent semper feugiat. Sed cras ornare arcu dui vivamus arcu. Sit amet consectetur adipiscing elit pellentesque habitant morbi. Aliquam etiam erat velit scelerisque in. Mattis enim ut tellus elementum. Sapien faucibus et molestie ac feugiat. Metus vulputate eu scelerisque felis imperdiet proin fermentum leo. Massa tincidunt dui ut ornare lectus sit amet. Et malesuada fames ac turpis egestas sed. Eget dolor morbi non arcu risus quis varius. Proin sagittis nisl rhoncus mattis rhoncus. Duis ultricies lacus sed turpis tincidunt id aliquet. Turpis egestas integer eget aliquet nibh praesent. Vel turpis nunc eget lorem dolor.

Auctor eu augue ut lectus arcu bibendum. Lorem mollis aliquam ut porttitor leo a diam sollicitudin tempor. Neque vitae tempus quam pellentesque nec. Vulputate eu scelerisque felis imperdiet. Sed lectus vestibulum mattis ullamcorper velit sed ullamcorper. Amet commodo nulla facilisi nullam vehicula ipsum a arcu. Malesuada bibendum arcu vitae elementum curabitur vitae nunc sed. Et magnis dis parturient montes nascetur. Mi bibendum neque egestas congue quisque egestas. Neque viverra justo nec ultrices. Diam maecenas ultricies mi eget mauris pharetra et ultrices. Pharetra convallis posuere morbi leo urna molestie at elementum eu. In vitae turpis massa sed elementum tempus egestas sed sed. Ultrices neque ornare aenean euismod elementum nisi quis eleifend. Aliquet lectus proin nibh nisl condimentum id venenatis a. Est lorem ipsum dolor sit.

Ut tortor pretium viverra suspendisse potenti nullam ac tortor vitae. Magnis dis parturient montes nascetur ridiculus mus mauris. Euismod in pellentesque massa placerat duis ultricies. Id velit ut tortor pretium. Etiam sit amet nisl purus in mollis nunc sed id. Quis imperdiet massa tincidunt nunc pulvinar sapien et ligula. Id ornare arcu odio ut. Id donec ultrices tincidunt arcu non sodales neque sodales. Non odio euismod lacinia at quis risus. Diam maecenas ultricies mi eget mauris. Eu non diam phasellus vestibulum lorem sed risus.

Adipiscing at in tellus integer feugiat scelerisque. Amet porttitor eget dolor morbi non arcu risus quis varius. Ullamcorper eget nulla facilisi etiam dignissim. Nullam ac tortor vitae purus faucibus ornare suspendisse. Vitae et leo duis ut diam quam. Sit amet nisl purus in mollis nunc sed id semper. Quis vel eros donec ac. Ipsum a arcu cursus vitae congue mauris rhoncus. Odio tempor orci dapibus ultrices. Nunc aliquet bibendum enim facilisis gravida neque convallis a cras. Id nibh tortor id aliquet.

Vestibulum lorem sed risus ultricies. Nibh mauris cursus mattis molestie a iaculis at. Augue neque gravida in fermentum. Mattis pellentesque id nibh tortor id aliquet lectus. Vitae tempus quam pellentesque nec nam aliquam sem et. Dolor sit amet consectetur adipiscing elit ut aliquam purus sit. A iaculis at erat pellentesque adipiscing commodo elit at imperdiet. Integer enim neque volutpat ac. Sit amet consectetur adipiscing elit duis tristique sollicitudin nibh. Diam in arcu cursus euismod quis viverra. At consectetur lorem donec massa sapien faucibus et molestie. Volutpat ac tincidunt vitae semper quis lectus nulla. In tellus integer feugiat scelerisque varius morbi enim. Dictum sit amet justo donec enim diam vulputate. Nisl nunc mi ipsum faucibus. Pharetra sit amet aliquam id diam maecenas ultricies mi eget. Cursus sit amet dictum sit amet justo donec. Nec nam aliquam sem et tortor consequat id. Erat pellentesque adipiscing commodo elit at imperdiet.</Text>
        </div>
    );
}